// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/auth/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.get').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/photo/:photo': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photo/[photo].delete').default>>>>
    }
    '/api/photo/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photo/add.post').default>>>>
    }
    '/api/portfolio/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portfolio/[id].delete').default>>>>
    }
    '/api/portfolio/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portfolio/all.get').default>>>>
    }
    '/api/portfolio/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portfolio/create.post').default>>>>
    }
    '/api/portfolio/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/portfolio/update.put').default>>>>
    }
    '/api/user/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id].get').default>>>>
    }
    '/api/user/create-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/create-otp.post').default>>>>
    }
    '/api/user/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/create.post').default>>>>
    }
    '/api/user/get-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/get-users.get').default>>>>
    }
    '/api/user/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/login.post').default>>>>
    }
    '/api/user/reset-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/reset-otp.post').default>>>>
    }
    '/api/user/set-balance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/set-balance.post').default>>>>
    }
    '/uploaded-img/:photo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/uploaded-img/[photo].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xml').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-robots/dist/runtime/nitro/server/robots-txt').default>>>>
    }
  }
}
export {}