import { createVuetify } from 'vuetify';
import {
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAppBarTitle,
  VAlert,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VBreadcrumbsDivider,
  VBtn,
  VBtnGroup,
  VBtnToggle,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardTitle,
  VCardItem,
  VCardText,
  VCarousel,
  VCarouselItem,
  VCheckbox,
  VChip,
  VChipGroup,
  VCol,
  VContainer,
  VDialog,
  VDivider,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelText,
  VExpansionPanelTitle,
  VFileInput,
  VFooter,
  VForm,
  VHover,
  VIcon,
  VImg,
  VInfiniteScroll,
  VInput,
  VItem,
  VItemGroup,
  VKbd,
  VLabel,
  VLayout,
  VLazy,
  VList,
  VListGroup,
  VListItem,
  VListItemTitle,
  VListItemSubtitle,
  VListItemAction,
  VListItemMedia,
  VLocaleProvider,
  VMain,
  VMenu,
  VMessages,
  VNavigationDrawer,
  VNoSsr,
  VOverlay,
  VParallax,
  VProgressCircular,
  VProgressLinear,
  VRadio,
  VRadioGroup,
  VRangeSlider,
  VResponsive,
  VRow,
  VSelect, // оставляем, ты используешь
  VSheet,
  VSlideGroup,
  VSlideGroupItem,
  VSlider,
  VSkeletonLoader,
  VSnackbar,
  VSpacer,
  VSwitch,
  VSystemBar,
  VTable,
  VTabs,
  VTab,
  VTextField,
  VTextarea,
  VThemeProvider,
  VToolbar,
  VToolbarTitle,
  VTooltip,
  VVirtualScroll,
} from 'vuetify/components';
import * as vuetifyDirectives from 'vuetify/directives';
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg';

export default defineNuxtPlugin((nuxtApp) => {
  const vuetify = createVuetify({
    components: {
      VApp,
      VAppBar,
      VAppBarNavIcon,
      VAppBarTitle,
      VAlert,
      VBreadcrumbs,
      VBreadcrumbsItem,
      VBreadcrumbsDivider,
      VBtn,
      VBtnGroup,
      VBtnToggle,
      VCard,
      VCardActions,
      VCardSubtitle,
      VCardTitle,
      VCardItem,
      VCardText,
      VCarousel,
      VCarouselItem,
      VCheckbox,
      VChip,
      VChipGroup,
      VCol,
      VContainer,
      VDialog,
      VDivider,
      VExpansionPanels,
      VExpansionPanel,
      VExpansionPanelText,
      VExpansionPanelTitle,
      VFileInput,
      VFooter,
      VForm,
      VHover,
      VIcon,
      VImg,
      VTable,
      VInfiniteScroll,
      VInput,
      VItem,
      VItemGroup,
      VKbd,
      VLabel,
      VLayout,
      VLazy,
      VList,
      VListGroup,
      VListItem,
      VListItemTitle,
      VListItemSubtitle,
      VListItemAction,
      VListItemMedia,
      VLocaleProvider,
      VMain,
      VMenu,
      VMessages,
      VNavigationDrawer,
      VNoSsr,
      VOverlay,
      VParallax,
      VProgressCircular,
      VProgressLinear,
      VRadio,
      VRadioGroup,
      VRangeSlider,
      VResponsive,
      VRow,
      VSelect, // оставляем, ты используешь
      VSheet,
      VSlideGroup,
      VSlideGroupItem,
      VSlider,
      VSkeletonLoader,
      VSnackbar,
      VSpacer,
      VSwitch,
      VSystemBar,
      VTabs,
      VTab,
      VTextField,
      VTextarea,
      VThemeProvider,
      VToolbar,
      VToolbarTitle,
      VTooltip,
      VVirtualScroll,
    },
    directives: vuetifyDirectives,
    ssr: true,
    defaults: {
      VBtn: {
        default: {
          color: '#f1aa34',
        },
      },
    },
    theme: {
      defaultTheme: 'dark',
    },
    icons: {
      defaultSet: 'mdi',
      aliases,
      sets: {
        mdi,
      },
    },
  });
  nuxtApp.vueApp.use(vuetify);
});
