
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CComplex': typeof import("../components/CComplex.vue")['default']
    'CFooter': typeof import("../components/CFooter.vue")['default']
    'CService': typeof import("../components/CService.vue")['default']
    'CSlider': typeof import("../components/CSlider.vue")['default']
    'ContactsBlock': typeof import("../components/ContactsBlock.vue")['default']
    'ImgBackground': typeof import("../components/ImgBackground.vue")['default']
    'MenuDesktop': typeof import("../components/MenuDesktop.vue")['default']
    'MenuMobile': typeof import("../components/MenuMobile.vue")['default']
    'PhoneInput': typeof import("../components/PhoneInput.vue")['default']
    'TextEditor': typeof import("../components/TextEditor.vue")['default']
    'VintersectAnimation': typeof import("../components/VintersectAnimation.vue")['default']
    'AuthFormAdmin': typeof import("../components/auth/AuthFormAdmin.vue")['default']
    'AuthFormUser': typeof import("../components/auth/AuthFormUser.vue")['default']
    'AuthIAmRaspezday': typeof import("../components/auth/AuthIAmRaspezday.vue")['default']
    'MainPageAboutUs': typeof import("../components/main-page/AboutUs.vue")['default']
    'MainPageAdvantages': typeof import("../components/main-page/Advantages.vue")['default']
    'MainPageBanner': typeof import("../components/main-page/Banner.vue")['default']
    'MainPageBonusProgram': typeof import("../components/main-page/BonusProgram.vue")['default']
    'MainPageComplexes': typeof import("../components/main-page/Complexes.vue")['default']
    'MainPageReview': typeof import("../components/main-page/Review.vue")['default']
    'MainPageTopServices': typeof import("../components/main-page/TopServices.vue")['default']
    'ModalLayout': typeof import("../components/modal/ModalLayout.vue")['default']
    'ModalLogin': typeof import("../components/modal/ModalLogin.vue")['default']
    'ModalPortfolio': typeof import("../components/modal/ModalPortfolio.vue")['default']
    'ModalSubmit': typeof import("../components/modal/ModalSubmit.vue")['default']
    'ModalLKPage': typeof import("../components/modal/modalLKPage.vue")['default']
    'ServicePagePriceTable': typeof import("../components/service-page/PriceTable.vue")['default']
    'ServicePageWrappingAdv': typeof import("../components/service-page/WrappingAdv.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'Motion': typeof import("@vueuse/motion")['MotionComponent']
    'MotionGroup': typeof import("@vueuse/motion")['MotionGroupComponent']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCComplex': typeof import("../components/CComplex.vue")['default']
    'LazyCFooter': typeof import("../components/CFooter.vue")['default']
    'LazyCService': typeof import("../components/CService.vue")['default']
    'LazyCSlider': typeof import("../components/CSlider.vue")['default']
    'LazyContactsBlock': typeof import("../components/ContactsBlock.vue")['default']
    'LazyImgBackground': typeof import("../components/ImgBackground.vue")['default']
    'LazyMenuDesktop': typeof import("../components/MenuDesktop.vue")['default']
    'LazyMenuMobile': typeof import("../components/MenuMobile.vue")['default']
    'LazyPhoneInput': typeof import("../components/PhoneInput.vue")['default']
    'LazyTextEditor': typeof import("../components/TextEditor.vue")['default']
    'LazyVintersectAnimation': typeof import("../components/VintersectAnimation.vue")['default']
    'LazyAuthFormAdmin': typeof import("../components/auth/AuthFormAdmin.vue")['default']
    'LazyAuthFormUser': typeof import("../components/auth/AuthFormUser.vue")['default']
    'LazyAuthIAmRaspezday': typeof import("../components/auth/AuthIAmRaspezday.vue")['default']
    'LazyMainPageAboutUs': typeof import("../components/main-page/AboutUs.vue")['default']
    'LazyMainPageAdvantages': typeof import("../components/main-page/Advantages.vue")['default']
    'LazyMainPageBanner': typeof import("../components/main-page/Banner.vue")['default']
    'LazyMainPageBonusProgram': typeof import("../components/main-page/BonusProgram.vue")['default']
    'LazyMainPageComplexes': typeof import("../components/main-page/Complexes.vue")['default']
    'LazyMainPageReview': typeof import("../components/main-page/Review.vue")['default']
    'LazyMainPageTopServices': typeof import("../components/main-page/TopServices.vue")['default']
    'LazyModalLayout': typeof import("../components/modal/ModalLayout.vue")['default']
    'LazyModalLogin': typeof import("../components/modal/ModalLogin.vue")['default']
    'LazyModalPortfolio': typeof import("../components/modal/ModalPortfolio.vue")['default']
    'LazyModalSubmit': typeof import("../components/modal/ModalSubmit.vue")['default']
    'LazyModalLKPage': typeof import("../components/modal/modalLKPage.vue")['default']
    'LazyServicePagePriceTable': typeof import("../components/service-page/PriceTable.vue")['default']
    'LazyServicePageWrappingAdv': typeof import("../components/service-page/WrappingAdv.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyMotion': typeof import("@vueuse/motion")['MotionComponent']
    'LazyMotionGroup': typeof import("@vueuse/motion")['MotionGroupComponent']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CComplex: typeof import("../components/CComplex.vue")['default']
export const CFooter: typeof import("../components/CFooter.vue")['default']
export const CService: typeof import("../components/CService.vue")['default']
export const CSlider: typeof import("../components/CSlider.vue")['default']
export const ContactsBlock: typeof import("../components/ContactsBlock.vue")['default']
export const ImgBackground: typeof import("../components/ImgBackground.vue")['default']
export const MenuDesktop: typeof import("../components/MenuDesktop.vue")['default']
export const MenuMobile: typeof import("../components/MenuMobile.vue")['default']
export const PhoneInput: typeof import("../components/PhoneInput.vue")['default']
export const TextEditor: typeof import("../components/TextEditor.vue")['default']
export const VintersectAnimation: typeof import("../components/VintersectAnimation.vue")['default']
export const AuthFormAdmin: typeof import("../components/auth/AuthFormAdmin.vue")['default']
export const AuthFormUser: typeof import("../components/auth/AuthFormUser.vue")['default']
export const AuthIAmRaspezday: typeof import("../components/auth/AuthIAmRaspezday.vue")['default']
export const MainPageAboutUs: typeof import("../components/main-page/AboutUs.vue")['default']
export const MainPageAdvantages: typeof import("../components/main-page/Advantages.vue")['default']
export const MainPageBanner: typeof import("../components/main-page/Banner.vue")['default']
export const MainPageBonusProgram: typeof import("../components/main-page/BonusProgram.vue")['default']
export const MainPageComplexes: typeof import("../components/main-page/Complexes.vue")['default']
export const MainPageReview: typeof import("../components/main-page/Review.vue")['default']
export const MainPageTopServices: typeof import("../components/main-page/TopServices.vue")['default']
export const ModalLayout: typeof import("../components/modal/ModalLayout.vue")['default']
export const ModalLogin: typeof import("../components/modal/ModalLogin.vue")['default']
export const ModalPortfolio: typeof import("../components/modal/ModalPortfolio.vue")['default']
export const ModalSubmit: typeof import("../components/modal/ModalSubmit.vue")['default']
export const ModalLKPage: typeof import("../components/modal/modalLKPage.vue")['default']
export const ServicePagePriceTable: typeof import("../components/service-page/PriceTable.vue")['default']
export const ServicePageWrappingAdv: typeof import("../components/service-page/WrappingAdv.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const Motion: typeof import("@vueuse/motion")['MotionComponent']
export const MotionGroup: typeof import("@vueuse/motion")['MotionGroupComponent']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCComplex: typeof import("../components/CComplex.vue")['default']
export const LazyCFooter: typeof import("../components/CFooter.vue")['default']
export const LazyCService: typeof import("../components/CService.vue")['default']
export const LazyCSlider: typeof import("../components/CSlider.vue")['default']
export const LazyContactsBlock: typeof import("../components/ContactsBlock.vue")['default']
export const LazyImgBackground: typeof import("../components/ImgBackground.vue")['default']
export const LazyMenuDesktop: typeof import("../components/MenuDesktop.vue")['default']
export const LazyMenuMobile: typeof import("../components/MenuMobile.vue")['default']
export const LazyPhoneInput: typeof import("../components/PhoneInput.vue")['default']
export const LazyTextEditor: typeof import("../components/TextEditor.vue")['default']
export const LazyVintersectAnimation: typeof import("../components/VintersectAnimation.vue")['default']
export const LazyAuthFormAdmin: typeof import("../components/auth/AuthFormAdmin.vue")['default']
export const LazyAuthFormUser: typeof import("../components/auth/AuthFormUser.vue")['default']
export const LazyAuthIAmRaspezday: typeof import("../components/auth/AuthIAmRaspezday.vue")['default']
export const LazyMainPageAboutUs: typeof import("../components/main-page/AboutUs.vue")['default']
export const LazyMainPageAdvantages: typeof import("../components/main-page/Advantages.vue")['default']
export const LazyMainPageBanner: typeof import("../components/main-page/Banner.vue")['default']
export const LazyMainPageBonusProgram: typeof import("../components/main-page/BonusProgram.vue")['default']
export const LazyMainPageComplexes: typeof import("../components/main-page/Complexes.vue")['default']
export const LazyMainPageReview: typeof import("../components/main-page/Review.vue")['default']
export const LazyMainPageTopServices: typeof import("../components/main-page/TopServices.vue")['default']
export const LazyModalLayout: typeof import("../components/modal/ModalLayout.vue")['default']
export const LazyModalLogin: typeof import("../components/modal/ModalLogin.vue")['default']
export const LazyModalPortfolio: typeof import("../components/modal/ModalPortfolio.vue")['default']
export const LazyModalSubmit: typeof import("../components/modal/ModalSubmit.vue")['default']
export const LazyModalLKPage: typeof import("../components/modal/modalLKPage.vue")['default']
export const LazyServicePagePriceTable: typeof import("../components/service-page/PriceTable.vue")['default']
export const LazyServicePageWrappingAdv: typeof import("../components/service-page/WrappingAdv.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyMotion: typeof import("@vueuse/motion")['MotionComponent']
export const LazyMotionGroup: typeof import("@vueuse/motion")['MotionGroupComponent']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
